// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CarLocationPoster is an autogenerated mock type for the CarLocationPoster type
type CarLocationPoster struct {
	mock.Mock
}

// PostCarLocation provides a mock function with given fields: lat, lon, carUUID
func (_m *CarLocationPoster) PostCarLocation(lat float64, lon float64, carUUID string) error {
	ret := _m.Called(lat, lon, carUUID)

	if len(ret) == 0 {
		panic("no return value specified for PostCarLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(float64, float64, string) error); ok {
		r0 = rf(lat, lon, carUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCarLocationPoster creates a new instance of CarLocationPoster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarLocationPoster(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarLocationPoster {
	mock := &CarLocationPoster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
