// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "carshare-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CarsGetter is an autogenerated mock type for the CarsGetter type
type CarsGetter struct {
	mock.Mock
}

// GetCars provides a mock function with given fields:
func (_m *CarsGetter) GetCars() ([]models.Car, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCars")
	}

	var r0 []models.Car
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Car, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Car); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Car)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCarsGetter creates a new instance of CarsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarsGetter {
	mock := &CarsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
