// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "carshare-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CarLocationsGetter is an autogenerated mock type for the CarLocationsGetter type
type CarLocationsGetter struct {
	mock.Mock
}

// GetCarLocations provides a mock function with given fields:
func (_m *CarLocationsGetter) GetCarLocations() ([]models.CarLocation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCarLocations")
	}

	var r0 []models.CarLocation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.CarLocation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.CarLocation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CarLocation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCarLocationsGetter creates a new instance of CarLocationsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarLocationsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarLocationsGetter {
	mock := &CarLocationsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
